### ISSUE TITLE
Bundle controller affected by DIExtraBundle

### ISSUE THREAD

**Issue by shieldo** [schmittjoh/JMSDiExtraBundle#126]
I have a controller class in a bundle that has explicitly not been included as one of the listed bundles DIExtraBundle should parse, and calls to this controller break because a proxy class (created by DIExtraBundle) is used that does not know about the controller's constructor arguments.  Why would this bundle be parsed when I haven't specified that this should happen?

Current config outline:

``` yaml
jms_di_extra:
    locations:
        all_bundles: false
        bundles:
            - 'SomeOtherBundle'
```

Specifically, the bundle in question in this instance is actually the SonataDoctrinePHPCRAdminBundle.

Any pointers?
