### ISSUE TITLE
Add support for Expression Language

### ISSUE THREAD

**Issue by slavafomin** [schmittjoh/JMSDiExtraBundle#158]
Consider adding support for [Expression Language](http://symfony.com/doc/current/components/expression_language/index.html).

For example I'm using this configuration:

``` yaml
jms_di_extra:
    automatic_controller_injections:
        properties:
            environment: "@=service('kernel').getEnvironment()"
```

It tells me that it can not find service with name `=service('kernel').getEnvironment()`.

Thanks )
