### ISSUE TITLE
pass parameters to service annotation

### ISSUE THREAD

**Issue by whitewhidow** [schmittjoh/JMSDiExtraBundle#162]
Hi, when using annotations to setup a service, is there a way that i can pass parameters to it from the parameters.yml file ? like i would in services.yml:

```
sam_pos.options:
        class: %sam_pos.options.class%
        arguments:
            branchId: %app_branchId%
            entityManager: "@doctrine.orm.entity_manager"
```

How would i pass `%branchId%`, coming from  `parameters.yml`
