### ISSUE TITLE
Injection of entity repository with @Service annotation does not work

### ISSUE THREAD

**Issue by Wirone** [schmittjoh/JMSDiExtraBundle#174]
I have controller action:

``` php
/**
 * @param Something $something
 * 
 * @Route("/somethings/{alias}", name="route_for_something")
 * @ParamConverter(
 *      "something",
 *      class = "SomethingBundle:Something",
 *      options = {
 *          "id" = "alias",
 *          "repository_method" = "getSomethingByAlias"
 *      }
 * )
 * @Method("GET")
 * @Template()
 */
public function somethingAction(Something $something) {
    // Works only to this moment, param is properly converted
    $somethings = $this->get('somethings_provider');
}
```

In `somethings_provider` service:

``` php
/**
 * @Service("somethings_provider")
 */
class SomethingsProvider {
    /**
     * @InjectParams({
     *     "somethingRepo" = @Inject("something_repository")
     * })
     */
    public function __construct($somethingRepo) {
        $this->somethingRepo = $somethingRepo;
    }
}
```

And here is problem: calling `$this->get('somethings_provider')` throws an error that argument 1 for `__construct()` in `SomethingRepository` is missing.

I have checked it by overriding `__construct()` in `SomethingRepository`. First call is from `@ParamConverter` and then arguments are fine (obviously, since `somethingAction()` is called). Second is from `@InjectParams` and then both parameters (`$em`, `$class`) are `null`.

When I define `something_repository` in `services.yml` instead of `@Service` annotation:

``` yaml
something_repository:
    class:           'X\YBundle\Entity\SomethingRepository'
    factory_service: doctrine.orm.entity_manager
    factory_method:  getRepository
    arguments:
        - 'X\YBundle\Entity\Something'
```

everything works fine.

Would be great to hear some feedback about it, @schmittjoh.

Please note I've changed namings because of secrecy of project.
