### ISSUE TITLE
How do I annotate Monolog?

### ISSUE THREAD

**Issue by miraage** [schmittjoh/JMSDiExtraBundle#205]
Config:
```yml
monolog:
  channels:
    - xxx
  handlers:
    vendor_xxx:
      type: stream
      level: debug
      path: "%kernel.logs_dir%/xxx_%kernel.environment%.log"
      channels: xxx
```

Service:
```php
/**
 * @Service
 * @Tag("monolog.logger", attributes = {"channel": "xxx"})
 */
class MyService
{
  private $logger;
  
  /**
   * @InjectParams({
   *  "logger" = @Inject("monolog.logger.vendor_xxx")
   * })
  */
  public function __construct(LoggerInterface $logger = null)
  {
    $this->logger = $logger;
  }
}
```

Still getting null.
