### ISSUE TITLE
Honor bundles configuration in controller injectors warmer

### ISSUE THREAD

**Issue by gremo** [schmittjoh/JMSDiExtraBundle#269]
Controller injectors warmer does not honor the `locations` configuration.

```yml
jms_di_extra:
    locations:
        all_bundles: false
        bundles: [AppBundle]
        directories: ["%kernel.root_dir%/../src"]
```

All directories are scanned (see [this line](https://github.com/schmittjoh/JMSDiExtraBundle/blob/master/HttpKernel/ControllerInjectorsWarmer.php#L49)) and this may causes issues with annotations, see [SonataUserBundle #686](https://github.com/sonata-project/SonataUserBundle/issues/686) and [SonataClassificationBundle #258](https://github.com/sonata-project/SonataClassificationBundle/issues/258).

May be the solution is injecting the `locations` configuration and filter out the bundles.
