### ISSUE TITLE
Custom automatic controller injection broken?

### ISSUE THREAD

**Issue by stevelacey** [schmittjoh/JMSDiExtraBundle#52]
The defaults of request and router seem to come through fine for me, but translator doesn't seem keen with this config, and request will still come through even if I remove it from the array:

```
jms_di_extra:
    locations:
        bundles: []
        directories: ["%kernel.root_dir%/../src"]

    automatic_controller_injections:
        properties:
            request: "@request"
            router: "@router"
            translator: "@translator"

        method_calls:
            setRouter: ["@router"]
```

Am I doing something wrong or is there a problem? JMSDiExtraExtension:configureAutomaticControllerInjections() is reading my config in correctly, but no error, and nothing is being passed to my controller action.
